### ISSUE TITLE
DIS TOOL

### ISSUE THREAD

**Issue by MihonZhu** [AF-GRILL/DISForUnrealExample#3]
How to start a dis scenario in external tool like video?

**Comment by AFRLGrill** [comment]
We used internal AFRL tools for our DIS recording and playback that we don't have the license to distribute. However, there are commercial tools that allow for DIS recording and playback. Some of which include:

AUV Workbench - Made by Naval Postgraduate School. We haven't used it, but it is open-source and has example missions.
MAK Data Logger - Commercial product. Comes with example DIS scenarios that can be replayed.

Other software can be used to generate DIS packets as well. Software like Prepar3D, X-Plane (with DIS plugin), or MACE can all be used to generate DIS network traffic.
